-- =============================================================================
-- Seed: S002__event_types.sql
-- Description: Reference rows for event_types (from provider event code catalog)
-- =============================================================================

INSERT INTO event_types (event_code, event_label, event_category, is_significant) VALUES
    ('101',  'Start 1st half',           'match_flow',  TRUE),
    ('102',  'End 1st half',             'match_flow',  TRUE),
    ('103',  'Start 2nd half',           'match_flow',  TRUE),
    ('104',  'End 2nd half',             'match_flow',  TRUE),
    ('105',  'Start Extra Time 1st',     'match_flow',  TRUE),
    ('106',  'End Extra Time 1st',       'match_flow',  TRUE),
    ('107',  'Start Extra Time 2nd',     'match_flow',  TRUE),
    ('108',  'End Extra Time 2nd',       'match_flow',  TRUE),
    ('109',  'Start Penalty Shootout',   'match_flow',  TRUE),
    ('129',  'Danger',                   'possession',  FALSE),
    ('133',  'Players coming out',       'match_flow',  FALSE),
    ('134',  'Players lined up',         'match_flow',  FALSE),
    ('136',  'Shake hands',              'match_flow',  FALSE),
    ('137',  'Coin flipping',            'match_flow',  FALSE),
    ('138',  'Minute of silence',        'match_flow',  FALSE),
    ('141',  'Game about to start',      'match_flow',  FALSE),
    ('148',  'Restart',                  'match_flow',  FALSE),
    ('187',  'Goal under investigation', 'var',          TRUE),
    ('207',  'Possible FK',              'set_piece',   FALSE),
    ('220',  'Close Market',             'market',      FALSE),
    ('221',  'Open Market',              'market',      FALSE),
    ('228',  'Possible TI',              'set_piece',   FALSE),
    ('258',  'Game conditions changed',  'match_flow',  FALSE),
    ('520',  'Lineup changed',           'lineup',      FALSE),
    ('524',  'Jersey colours updated',   'lineup',      FALSE),
    ('532',  'Formation changed',        'lineup',      FALSE),
    ('533',  'VAR Start',                'var',          TRUE),
    ('535',  'VAR Event: Goal',          'var',          TRUE),
    ('536',  'VAR Stop',                 'var',          TRUE),
    ('540',  'Possible VAR',             'var',          FALSE),
    ('541',  'Possible VAR Event: Goal', 'var',          TRUE),
    ('542',  'VAR Review Cause: Foul',   'var',          TRUE),
    ('1024', 'AT (Attack)',              'attack',       FALSE),
    ('1026', 'DAT (Dangerous Attack)',   'attack',       FALSE),
    ('1027', 'DFK (Dangerous FK)',       'set_piece',   FALSE),
    ('1028', 'FK',                       'set_piece',   FALSE),
    ('1039', 'SH (on target)',           'shot',         TRUE),
    ('1042', 'Foul',                     'discipline',  FALSE),
    ('1043', 'Offside',                  'general',     FALSE),
    ('1051', 'Safe',                     'possession',  FALSE),
    ('1052', 'Danger',                   'possession',  FALSE),
    ('1054', 'TI (Throw in)',            'set_piece',   FALSE),
    ('1058', 'BLOCK',                    'shot',         FALSE),
    ('1066', 'Possible CR',              'set_piece',   FALSE),
    ('1071', 'Possible FK (Home)',       'set_piece',   FALSE),
    ('1073', 'Possible TI (Home)',       'set_piece',   FALSE),
    ('1074', 'Safe Center',              'possession',  FALSE),
    ('1075', 'Attack Center',            'attack',      FALSE),
    ('1076', 'Danger Right',             'possession',  FALSE),
    ('2048', 'AT (Away)',                'attack',      FALSE),
    ('2049', 'CR (Corner)',              'set_piece',   FALSE),
    ('2050', 'DAT (Away)',               'attack',      FALSE),
    ('2051', 'DFK (Away)',               'set_piece',   FALSE),
    ('2052', 'FK (Away)',                'set_piece',   FALSE),
    ('2053', 'Goal',                     'goal',         TRUE),
    ('2054', 'Cancel Goal',              'goal',         TRUE),
    ('2063', 'SH (on target, Away)',     'shot',         TRUE),
    ('2065', 'SH (woodwork, Away)',      'shot',         TRUE),
    ('2066', 'Foul (Away)',              'discipline',  FALSE),
    ('2067', 'Offside (Away)',           'general',     FALSE),
    ('2075', 'Safe (Away)',              'possession',  FALSE),
    ('2076', 'Danger (Away)',            'possession',  FALSE),
    ('2077', 'GK (Goal Kick)',           'set_piece',   FALSE),
    ('2078', 'TI (Away)',                'set_piece',   FALSE),
    ('2082', 'BLOCK (Away)',             'shot',         FALSE),
    ('2090', 'Possible CR (Away)',       'set_piece',   FALSE),
    ('2095', 'Possible FK (Away)',       'set_piece',   FALSE),
    ('2097', 'Possible TI (Away)',       'set_piece',   FALSE),
    ('2098', 'Safe Center (Away)',       'possession',  FALSE),
    ('2099', 'Attack Right (Away)',      'attack',      FALSE),
    ('2100', 'Danger Left (Away)',       'possession',  FALSE)
ON CONFLICT (event_code) DO NOTHING;
